export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MENU_ROUTE = '/menu'
export const DISH_ROUTE = '/dish'
export const HOME_ROUTE = '/'
export const ABOUT_ROUTE = '/aboutUs'
export const CONTACT_ROUTE = '/contact'
export const ORDER_ROUTE = '/orders'
export const RESERVE_ROUTE = '/reserve'

